import type { Field, FieldPoint, Member, RecordItem, ScheduleItem } from "./types";

export const fields: Field[] = [
  {
    id: "field-a",
    name: "A田",
    label: "A田",
    area: "1.2ha",
    crop: "コシヒカリ",
    season: "分げつ期",
    color: "blue",
  },
  {
    id: "field-b",
    name: "B田",
    label: "B田",
    area: "0.8ha",
    crop: "コシヒカリ",
    season: "活着期",
    color: "yellow",
  },
  {
    id: "field-c",
    name: "C田",
    label: "C田",
    area: "1.5ha",
    crop: "新之助",
    season: "分げつ期",
    color: "green",
  },
  {
    id: "field-d",
    name: "D田",
    label: "D田",
    area: "0.9ha",
    crop: "こしいぶき",
    season: "初期",
    color: "purple",
  },
];

export const fieldPoints: FieldPoint[] = [
  {
    id: "point-a-inlet-east",
    fieldId: "field-a",
    name: "A田 東側 入水口",
    type: "inlet",
    status: "normal",
    lastRecord: "2025年5月24日 08:15",
    waterLevel: "正常",
    position: { x: 20, y: 39 },
  },
  {
    id: "point-b-inlet-north",
    fieldId: "field-b",
    name: "B田 北側 入水口",
    type: "inlet",
    status: "normal",
    lastRecord: "2025年5月24日 07:45",
    waterLevel: "正常",
    position: { x: 55, y: 25 },
  },
  {
    id: "point-b-outlet-east",
    fieldId: "field-b",
    name: "B田 東側 出水口",
    type: "outlet",
    status: "normal",
    lastRecord: "2025年5月23日 16:20",
    waterLevel: "やや少なめ",
    position: { x: 80, y: 39 },
  },
  {
    id: "point-c-caution",
    fieldId: "field-c",
    name: "C田 中央東側 水位異常",
    type: "caution",
    status: "needs_check",
    lastRecord: "2025年5月24日 10:15",
    waterLevel: "高め",
    position: { x: 58, y: 55 },
  },
  {
    id: "point-c-outlet",
    fieldId: "field-c",
    name: "C田 南側 出水口",
    type: "outlet",
    status: "normal",
    lastRecord: "2025年5月22日 09:05",
    waterLevel: "正常",
    position: { x: 51, y: 75 },
  },
  {
    id: "point-d-outlet",
    fieldId: "field-d",
    name: "D田 西側 出水口",
    type: "outlet",
    status: "normal",
    lastRecord: "2025年5月23日 09:05",
    waterLevel: "正常",
    position: { x: 17, y: 76 },
  },
];

export const scheduleItems: ScheduleItem[] = [
  { time: "08:00", title: "A田 取水確認", fieldName: "A田（1.2ha）", icon: "drop", status: "予定" },
  { time: "10:30", title: "B田 中干し確認", fieldName: "B田（0.8ha）", icon: "waves", status: "進行中" },
  { time: "13:30", title: "C田 畦畔草刈り", fieldName: "C田（1.5ha）", icon: "sprout", status: "予定" },
];

export const recentRecords: RecordItem[] = [
  {
    id: "record-1",
    time: "17:15",
    date: "2025年5月24日（土）",
    title: "A田 取水口の確認",
    fieldName: "A田",
    fieldArea: "1.2ha",
    category: "水管理",
    pointType: "inlet",
    media: "photo",
    photoCount: 3,
  },
  {
    id: "record-2",
    time: "13:30",
    date: "2025年5月24日（土）",
    title: "C田 畦畔草刈り",
    fieldName: "C田",
    fieldArea: "1.5ha",
    category: "作業",
    pointType: "weed",
    media: "photo",
    photoCount: 5,
  },
  {
    id: "record-3",
    time: "10:15",
    date: "2025年5月24日（土）",
    title: "B田 異常箇所の記録",
    fieldName: "B田",
    fieldArea: "0.8ha",
    category: "異常",
    pointType: "caution",
    media: "photo",
    photoCount: 2,
  },
  {
    id: "record-4",
    time: "08:00",
    date: "2025年5月24日（土）",
    title: "A田 圃場の状況メモ",
    fieldName: "A田",
    fieldArea: "1.2ha",
    category: "音声",
    pointType: "inlet",
    media: "audio",
    audioDuration: "0:32",
  },
  {
    id: "record-5",
    time: "16:20",
    date: "2025年5月23日（金）",
    title: "B田 落水口の確認",
    fieldName: "B田",
    fieldArea: "0.8ha",
    category: "水管理",
    pointType: "outlet",
    media: "photo",
    photoCount: 1,
  },
  {
    id: "record-6",
    time: "11:40",
    date: "2025年5月23日（金）",
    title: "A田 畦畔草刈り",
    fieldName: "A田",
    fieldArea: "1.2ha",
    category: "作業",
    pointType: "weed",
    media: "photo",
    photoCount: 4,
  },
];

export const members: Member[] = [
  { name: "作業者A（あなた）", role: "管理者" },
  { name: "作業者B", role: "編集者" },
  { name: "作業者C", role: "閲覧者" },
];
